### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sachinrastogi12**
Hi team,

I wanted to share with you some of the best VS code extensions that I have personally used, and I think they would be a valuable addition to our resource repository. Could you please merge these extensions into the repository? If there are any changes or modifications you would like me to make, please let me know.

Thank you.

### CODE REVIEW

**Comment by Satendra-SR** [comment]
Thanks, @sachinrastogi12 for raising the PR. Let's add them to a better folder hierarchy.
What about this?
```js
software-practices > Code Editors > VS Code > Recommended Extentions
```

**Comment by sachinrastogi12** [comment]
Hello sir, please check the PR I have made a few changes accordingly. And let me if it is in a structured way now.

**Review by Satendra-SR — APPROVED** [review]

**Comment by Satendra-SR** [comment]
Looks good @sachinrastogi12, congratulation on your first commit on the ColoredCow Resources repository 🎉

**Comment by sachinrastogi12** [comment]
Thank you so much @Satendra-SR 🥳

**Pull request merged**
